(function(){
var cityData={
 seoul:{name:'서울',mode:'verified',note:'2026 상반기 외국인 방문 823만 · 카드소비 5조6,172억 · 1인당 카드소비 약 68만원',stats:[['823만','상반기 외국인 방문'],['₩5.62조','외국인 카드소비'],['68만원','1인당 카드소비']],areas:[['명동','유동 신호 매우 높음','100,910명/일','high'],['삼성·코엑스','관광·MICE·쇼핑','46,813명/일','high'],['강남·신논현','의료·뷰티·쇼핑','41,210명/일','high'],['홍대','문화·쇼핑·야간','40,213명/일','high'],['동대문·DDP','쇼핑·패션·야간','외국인 비중 19.6%','high'],['이태원','글로벌 상권','탐색 우선','high'],['성수','로컬·뷰티·패션','탐색 우선','medium'],['종로·북촌','역사·문화','탐색 우선','medium']]},
 busan:{name:'부산',mode:'verified',note:'2026년 6월 누계 외국인 242만 · 전년 동기 대비 +43.9% · 외국인 지출 6,239억',stats:[['242만','외국인 방문 누계'],['+43.9%','전년 동기 대비'],['₩6,239억','외국인 지출']],areas:[['해운대','숙박·해변·MICE','관광 핵심 동선','high'],['광안리','야간·해변·F&B','관광 핵심 동선','high'],['남포·자갈치','시장·음식·원도심','관광 핵심 동선','high'],['서면','쇼핑·뷰티·야간','도심 소비 동선','high'],['부산역·초량','교통·원도심','환승·관광 동선','medium'],['센텀시티','MICE·쇼핑','목적 방문 동선','medium'],['송정','해변·카페','관광 동선','medium']]},
 jeju:{name:'제주',mode:'verified',note:'2026년 6월 누계 외국인 120만4,783명 · 전년 동기 대비 +18.6%',stats:[['120만','외국인 방문 누계'],['+18.6%','전년 동기 대비']],areas:[['제주시·연동','공항·쇼핑·숙박','도심 핵심 동선','high'],['애월','카페·해안·숙박','목적 관광 동선','high'],['서귀포·중문','리조트·숙박·관광','목적 방문 강함','high'],['성산','성산일출봉·동부 관광','관광 동선','high'],['함덕','해변·카페·숙박','관광 동선','medium'],['동문시장','시장·음식·쇼핑','관광 동선','medium']]},
 gyeongju:{name:'경주',mode:'verified',note:'2026 상반기 외국인 70만7,197명 · 전년 동기 대비 +19.0%',stats:[['70.7만','상반기 외국인 방문'],['+19.0%','전년 동기 대비']],areas:[['황리단길·대릉원','역사·F&B·로컬','관광 핵심 동선','high'],['동부사적지·황룡사지','역사·문화','외국인 현장 체감 증가','high'],['보문단지','숙박·MICE·리조트','목적 방문 강함','high'],['불국사','역사·문화','목적 관광 동선','medium'],['경주역·시내','교통·F&B','환승·도심 동선','medium']]},
 incheon:{name:'인천',mode:'signal',note:'2026 인천관광공사 전략: 공항·환승·크루즈·개항장·송도 등 글로벌 관광 허브 강화',stats:[],areas:[['영종·인천공항','환승·숙박·공항','외국인 접점 강함','high'],['송도','MICE·비즈니스·숙박','목적 방문 강함','high'],['개항장·차이나타운','역사·음식·관광','관광 동선','high'],['월미도','관광·F&B','관광 동선','medium'],['구월동','쇼핑·뷰티·F&B','도심 소비 동선','medium'],['부평','쇼핑·F&B','도심 상권','medium']]},
 gangneung:{name:'강릉',mode:'signal',note:'정량 수치는 단계적으로 연결 중 · 관광·교통 동선 중심 탐색',stats:[],areas:[['강릉역·중앙시장','교통·시장·F&B','도심 관광 동선','high'],['경포','해변·숙박·관광','관광 핵심 동선','high'],['안목','카페·해변','목적 방문 동선','high'],['주문진','시장·해변·콘텐츠','관광 동선','medium'],['교동','로컬·F&B','도심 상권','medium'],['정동진','관광·숙박','목적 관광 동선','medium']]},
 sokcho:{name:'속초',mode:'signal',note:'외국인 관광택시·다국어 관광안내 운영 · 설악산·시장·해변·항만을 연결하는 목적 관광 도시',stats:[],areas:[['속초관광수산시장','시장·음식·쇼핑','관광 핵심 동선','high'],['속초해수욕장·터미널','해변·교통·숙박','관광 핵심 동선','high'],['설악산·설악동','자연·체험·숙박','목적 방문 강함','high'],['대포항','해산물·항구·숙박','관광 동선','medium'],['아바이마을','문화·음식·체험','관광 동선','medium'],['동명항·크루즈','항만·크루즈','외국인 접점','medium']]},
 chuncheon:{name:'춘천',mode:'signal',note:'외국인 관광택시 운영 · 춘천역에서 주요 관광지를 연결하는 목적 방문 동선 확인 가능',stats:[],areas:[['춘천역','교통·관광 출발점','외국인 관광택시 출발','high'],['소양강 스카이워크','관광·전망','관광 동선','medium'],['육림고개·중앙시장','시장·음식·로컬','관광 동선','medium'],['구봉산 카페거리','카페·전망','목적 방문 동선','medium'],['애니메이션박물관','가족·체험','목적 방문 동선','medium'],['김유정문학마을','문화·체험','목적 관광 동선','medium']]},
 jeonju:{name:'전주',mode:'signal',note:'전주역→한옥마을→전라감영 등 외국인 여정 단위 관광 편의 개선 정책 추진',stats:[],areas:[['한옥마을','전통·음식·체험','관광 핵심 동선','high'],['전주역','교통·관광 출발점','환승 동선','medium'],['전라감영·객사','역사·문화','관광 동선','medium'],['남부시장·청년몰','시장·F&B','관광 동선','medium'],['풍남문','역사·한옥마을 연계','관광 동선','medium'],['객리단길','로컬·F&B','도심 상권','medium']]},
 daegu:{name:'대구',mode:'signal',note:'정량 수치는 단계적으로 연결 중 · 도심 쇼핑·시장·의료·교통 상권 중심 탐색',stats:[],areas:[['동성로','쇼핑·뷰티·F&B','도심 핵심 상권','high'],['서문시장','시장·음식·쇼핑','관광 동선','high'],['동대구역','교통·숙박·환승','외부 유입 동선','medium'],['수성못','F&B·야간·관광','목적 방문 동선','medium'],['김광석길','문화·관광','관광 동선','medium'],['두류·이월드','체험·관광','목적 방문 동선','medium']]}
};
var industryData={food:{name:'음식점',dest:'medium'},massage:{name:'마사지·스파',dest:'high'},beauty:{name:'뷰티·헤어',dest:'high'},clinic:{name:'병의원·의료',dest:'high'},stay:{name:'숙박',dest:'high'},cafe:{name:'카페·디저트',dest:'medium'},experience:{name:'체험·관광',dest:'high'},retail:{name:'쇼핑·소매',dest:'medium'}};
var selected={city:null,area:null,industry:null,presence:null};
var cities=document.getElementById('cities'),areas=document.getElementById('areas'),industries=document.getElementById('industries'),cityEvidence=document.getElementById('cityEvidence');
Object.keys(cityData).forEach(function(k){var c=cityData[k],b=document.createElement('button');b.className='selBtn';b.dataset.city=k;b.textContent=c.name;b.onclick=function(){chooseCity(k,b)};cities.appendChild(b)});
Object.keys(industryData).forEach(function(k){var d=industryData[k],b=document.createElement('button');b.className='industryBtn';b.dataset.industry=k;b.textContent=d.name;b.onclick=function(){industries.querySelectorAll('button').forEach(function(x){x.classList.remove('on')});b.classList.add('on');selected.industry=k;document.getElementById('presenceStage').classList.add('show');renderLocal()};industries.appendChild(b)});
function chooseCity(k,b){cities.querySelectorAll('button').forEach(function(x){x.classList.remove('on')});b.classList.add('on');selected.city=k;selected.area=null;selected.industry=null;selected.presence=null;var c=cityData[k];var html='<div class="eviTop"><div><div class="eviTitle">'+c.name+' · 지역 신호</div></div><span class="dataBadge">'+(c.mode==='verified'?'공식 통계 연결됨':'상권 신호 중심')+'</span></div>';if(c.stats.length){html+='<div class="eviStats">'+c.stats.map(function(s){return '<div class="eviStat"><b>'+s[0]+'</b><span>'+s[1]+'</span></div>'}).join('')+'</div>'}html+='<div class="eviNote">'+c.note+'</div>';cityEvidence.innerHTML=html;cityEvidence.classList.add('show');areas.innerHTML='';c.areas.forEach(function(a,i){var x=document.createElement('button');x.className='areaBtn';x.innerHTML='<b>'+a[0]+'</b><span>'+a[1]+' · <span class="'+(a[2].indexOf('명/일')>-1?'daily':'')+'">'+a[2]+'</span></span>';x.onclick=function(){areas.querySelectorAll('button').forEach(function(y){y.classList.remove('on')});x.classList.add('on');selected.area=i;document.getElementById('industryStage').classList.add('show');renderLocal()};areas.appendChild(x)});document.getElementById('areaStage').classList.add('show');document.getElementById('industryStage').classList.remove('show');document.getElementById('presenceStage').classList.remove('show');document.getElementById('signalResult').classList.remove('show');updateReply()}
document.getElementById('presence').onclick=function(e){var b=e.target.closest('button');if(!b)return;document.querySelectorAll('#presence button').forEach(function(x){x.classList.remove('on')});b.classList.add('on');selected.presence=b.dataset.presence;renderLocal();updateReply()};
function label(v){return v==='high'?['HIGH','sigHigh']:v==='medium'?['MEDIUM','sigMed']:['LOW','sigLow']}
function renderLocal(){if(!selected.city||selected.area===null||!selected.industry||!selected.presence)return;var c=cityData[selected.city],a=c.areas[selected.area],ind=industryData[selected.industry],passing=a[3],dest=ind.dest,search='high';if(selected.presence==='rare'&&dest==='medium')search='medium';var p=label(passing),d=label(dest),s=label(search);document.getElementById('passing').textContent=p[0];document.getElementById('passing').className=p[1];document.getElementById('destination').textContent=d[0];document.getElementById('destination').className=d[1];document.getElementById('searchImportance').textContent=s[0];document.getElementById('searchImportance').className=s[1];document.getElementById('localTitle').textContent=c.name+' · '+a[0]+' · '+ind.name;var text='';if(passing==='high'&&selected.presence!=='rare'){text='이미 지나가는 수요가 있는 자리입니다. 새 외국인을 만드는 것보다 <strong>이미 근처에 있는 사람이 검색 후보에서 우리 매장을 발견하고 이해하는지</strong>를 먼저 볼 가치가 있습니다.'}else if(selected.presence==='rare'&&dest==='high'){text='외국인이 많이 지나가지 않아도 됩니다. '+ind.name+'은(는) 목적 방문 가능성이 있는 업종이라, <strong>검색해서 찾아갈 이유가 지도·사진·리뷰·예약 정보에서 보이는지</strong>가 더 중요합니다.'}else if(selected.presence==='rare'&&dest==='medium'){text='이 경우 외국인 광고가 우선순위가 아닐 수도 있습니다. 먼저 <strong>기본 영문·지도 정보만 정합하게 두고, 실제 외국인 문의나 주변 관광 동선이 생기는지</strong>를 확인하는 편이 합리적입니다.'}else{text='외국인 수요가 아예 없는 자리라기보다, 유동과 목적 방문이 섞여 있는 구간입니다. <strong>어디서 발견했고 무엇을 물어본 뒤 방문했는지</strong>를 기록하면 반복할 신호를 찾을 수 있습니다.'}document.getElementById('interpret').innerHTML=text;document.getElementById('signalResult').classList.add('show');document.getElementById('reportMeta').textContent=c.name+' · '+a[0]+' · '+ind.name;document.getElementById('reportLocal').textContent=c.name+' · '+a[0];updateReply()}
function updateReply(){var c=selected.city?cityData[selected.city].name:'____',a=(selected.city&&selected.area!==null)?cityData[selected.city].areas[selected.area][0]:'____',i=selected.industry?industryData[selected.industry].name:'____',p=selected.presence==='often'?'자주 보임':selected.presence==='sometimes'?'가끔 보임':selected.presence==='rare'?'거의 없음':'____';document.getElementById('text').textContent='매장명: ____ / 지역: '+c+' / 상권: '+a+' / 업종: '+i+' / 외국인 손님: '+p+' / 자주 묻는 것: ____'}
var bar=document.getElementById('bar');function sc(){var d=document.documentElement,m=d.scrollHeight-d.clientHeight;bar.style.width=(m?d.scrollTop/m*100:0)+'%'}addEventListener('scroll',sc,{passive:true});sc();var ans={a:null,b:null,c:null},q=document.getElementById('quiz');q.onclick=function(e){var x=e.target.closest('.opt');if(!x)return;x.parentNode.querySelectorAll('.opt').forEach(function(z){z.classList.remove('sel')});x.classList.add('sel');ans[x.dataset.k]=+x.dataset.v;if(Object.values(ans).every(function(v){return v!==null}))document.getElementById('go').classList.add('show')};document.getElementById('show').onclick=function(){var sum=ans.a+ans.b+ans.c,t,c;if(sum===3){t='기본기는 이미 잘 잡혀 있습니다.';c='이제 외국인 손님이 실제로 어디서 발견하고 어떤 검색어로 들어오는지 확인하면 다음 방향이 보입니다.'}else if(sum===2){t='한두 화면만 맞추면 훨씬 선명해집니다.';c='정보가 한 화면에서 이어지지 않는 지점만 찾아 맞추면 방문 전 망설임을 더 줄일 수 있습니다.'}else if(sum===1){t='확인 근거를 정리할 여지가 있습니다.';c='수요가 없다고 보기보다, 발견한 뒤 매장을 이해하고 안심할 근거가 충분히 보이는지부터 확인하는 편이 좋습니다.'}else{t='지금이 현재 화면을 확인해보기 좋은 시점입니다.';c='큰 광고보다 Google·Maps·Photos·Reviews·Booking에서 무엇이 보이고 비어 있는지부터 순서대로 보면 됩니다.'}document.getElementById('rt').textContent=t;document.getElementById('rc').textContent=c;document.getElementById('result').classList.add('show');document.getElementById('go').style.display='none'};
document.getElementById('copy').onclick=function(){var t=document.getElementById('text').textContent,done=function(){var z=document.getElementById('toast');z.classList.add('on');setTimeout(function(){z.classList.remove('on')},1800)};if(navigator.clipboard&&navigator.clipboard.writeText)navigator.clipboard.writeText(t).then(done).catch(done);else done()};
})();
